# Generated by Buildr 1.4.1, change to your liking
# Version number for this release
Buildr.settings.build['scala.version'] = "2.8.0.RC7"
require 'buildr/scala'
VERSION_NUMBER = "1.0.0"
# Group identifier for your projects
GROUP = "StupidCode"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"
desc "The Stupidcode project"
Project.local_task :main
define "StupidCode" do
  compile.using :make => :transitive
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  task :main do
       system "java -cp #{compile.dependencies.clone.add('target/classes').join(File::PATH_SEPARATOR)} Main"
  end
end
